name: Docker Build

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - "airflow/**"

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build Airflow Docker image
        run: |
          docker build --no-cache -t mediwatch-airflow:test -f airflow/Dockerfile airflow/
